const hardPromptGroups = [
  {
    id: "tired-parents-low-crowd",
    intent: "family low crowd low walking",
    interests: ["family", "low-energy", "quiet"],
    constraints: { groupType: "family", crowdLevel: "low", energyLevel: "low", pace: "slow" },
    relevantSourceIds: ["delhi_001", "karnataka_003", "goa_008", "goa_003", "andaman_002", "kerala_002", "rajasthan_004"],
    queries: [
      "I hate crowded places and my parents get tired quickly",
      "need something my mom can enjoy without walking forever",
      "dad has knee pain, please avoid packed tourist chaos",
      "quiet place for parents, not a checklist trip",
      "parents are coming and they get exhausted after lunch",
      "low crowd holiday, elders with us, short walks only",
      "family trip but no pushing through huge lines",
      "somewhere calm where older parents can sit and still enjoy",
      "not too much walking, not too loud, parents friendly",
      "my parents want pretty places but they tire fast",
      "elder friendly vacation that doesn't feel boring",
      "quiet scenic trip for family, no intense trekking",
      "avoid crowds and stairs, parents are sensitive to heat",
      "family wants relaxed sightseeing, not a marathon",
      "parents plus kids, need easy movement and calm places",
      "I want peaceful and accessible, no crazy crowds",
      "dad wants nature but cannot do long hikes",
      "mom wants gardens and views, I want low stress",
      "please avoid over-touristy places for my parents",
      "slow family vacation where nobody gets drained"
    ]
  },
  {
    id: "messy-friends-budget",
    intent: "friends budget mixed interests",
    interests: ["friends", "budget", "photography", "food"],
    constraints: { groupType: "friends", budgetBand: "low", pace: "balanced" },
    relevantSourceIds: ["karnataka_002", "himachal_002", "karnataka_001", "maharashtra_001", "goa_004", "goa_007", "delhi_001"],
    queries: [
      "5 friends, one vegetarian, one photographer, budget 30k",
      "group of friends, cheap trip, need photos and decent food",
      "we're broke but one friend wants nice sunset shots",
      "five people, not luxury, vegetarian food should be easy",
      "budget group trip where photos don't look boring",
      "friends want cafes, views, and not spending too much",
      "student-ish budget, group vibe, one camera obsessed friend",
      "cheap trip for friends, food options matter a lot",
      "group wants fun but not clubs every night",
      "budget 30k total-ish, friends, vegetarian safe",
      "friends trip with photos, markets, and low cost stays",
      "we need something social but still affordable",
      "one friend only cares about reels, one about food, keep it cheap",
      "five friends, mixed interests, avoid premium resorts",
      "budget friendly destination with sunset and cafe options",
      "friend group wants memories, not expensive transfers",
      "cheap but pretty place for college friends",
      "friends need veg food, viewpoints, and hostel-ish costs",
      "group vacation under tight budget with photo spots",
      "affordable friends trip, some food some views some chill"
    ]
  },
  {
    id: "not-hot-june",
    intent: "cool weather in June",
    interests: ["cool weather", "hills", "nature"],
    constraints: { month: "jun", season: "summer", climatePreference: "cool" },
    relevantSourceIds: ["himachal_003", "himachal_002", "kerala_003", "karnataka_003", "arunachal_001", "himachal_001", "meghalaya_001"],
    queries: [
      "somewhere not too hot in June",
      "June trip but I cannot handle heat",
      "where can we go in June that isn't boiling",
      "need a cool-ish place for early June",
      "avoid sweaty weather in June please",
      "June vacation, pleasant climate, no beaches if too humid",
      "not hot not dusty, travelling in June",
      "cool weather destination around June for 4 days",
      "I want hills or something breathable in June",
      "June plan, temperature matters more than nightlife",
      "family wants pleasant June weather",
      "summer break but please not 35 degrees",
      "we can travel in June only, need cool climate",
      "not too hot in June and good views",
      "June escape from heat with nature",
      "where is comfortable in June without spending crazy money",
      "want cooler weather in June, okay with mountains",
      "June trip for parents, avoid heat stroke vibes",
      "somewhere mild in June with scenery",
      "heat sensitive traveler, June itinerary ideas"
    ]
  },
  {
    id: "visited-goa-exclusion",
    intent: "exclude already visited Goa",
    interests: ["beach", "sunset", "romantic", "quiet"],
    constraints: { excludedDestinations: ["Goa"], crowdLevel: "low", pace: "slow" },
    relevantSourceIds: ["kerala_001", "karnataka_002", "andaman_001", "andaman_002", "rajasthan_004"],
    queries: [
      "we've already been to Goa twice",
      "not Goa again, but we still want beach vibes",
      "done Goa already, suggest something calmer",
      "we liked Goa but want a different coastal trip",
      "please don't send us back to Goa",
      "been to Goa twice, need a fresh sunset place",
      "not north Goa, not south Goa, something else",
      "we're bored of Goa but still want a relaxed vacation",
      "no Goa this time, couple trip with views",
      "Goa is overdone for us, what else works",
      "skip Goa, want quiet beach or water views",
      "already did Goa parties, now want calm sunsets elsewhere",
      "not Goa, fewer crowds, maybe cliffs or islands",
      "Goa twice done, need a romantic alternative",
      "avoid Goa completely, coastal and peaceful is okay",
      "want beach energy without repeating Goa",
      "Goa fatigue, suggest a different vibe",
      "anything except Goa for a slow couple trip",
      "we know Goa too well, surprise us with another place",
      "not Goa but similar chill evenings"
    ]
  },
  {
    id: "vague-romantic-sunset",
    intent: "vague romantic sunset",
    interests: ["romantic", "sunset", "scenic"],
    constraints: { groupType: "couples", timeOfDay: "sunset", pace: "slow" },
    relevantSourceIds: ["goa_002", "goa_003", "kerala_001", "rajasthan_004", "rajasthan_003", "andaman_001", "andaman_002", "goa_007"],
    queries: [
      "my girlfriend likes sunsets",
      "planning something cute, she loves golden hour",
      "need a pretty evening place for my partner",
      "not proposing, but romantic sunset vibes",
      "couple trip where evenings feel special",
      "she wants views and I don't want chaos",
      "romantic but not cheesy, sunset would help",
      "girlfriend likes calm water and photos",
      "anniversary-ish trip with sunset scenes",
      "need one place that feels romantic after 5pm",
      "couple vacation, good evening light, not too crowded",
      "want to impress her with a sunset spot",
      "slow trip with pretty skies and cafes",
      "she likes beaches and sunsets but not parties",
      "romantic views, relaxed budget, winter maybe",
      "evening walks, sunsets, couple friendly",
      "something scenic for two people who hate rushing",
      "soft romantic trip with photos",
      "sunset and quiet dinner kind of vacation",
      "partner wants beautiful views, I need easy planning"
    ]
  },
  {
    id: "contradictory-party-quiet",
    intent: "contradictory nightlife and quiet",
    interests: ["nightlife", "quiet", "food"],
    constraints: { groupType: "friends", crowdLevel: "low", timeOfDay: "evening" },
    relevantSourceIds: ["goa_004", "maharashtra_001", "himachal_002", "kerala_001", "goa_002", "goa_007"],
    queries: [
      "we want nightlife but also hate crowds",
      "friends want bars, I want quiet mornings",
      "party one night, peaceful the next day",
      "social evening but not packed clubs",
      "fun group trip without full chaos",
      "some nightlife but no loud beach crowd",
      "evening food scene, not wild partying",
      "friends want energy, I need downtime",
      "mixed group: two party people, two introverts",
      "want cafes and bars but not overcrowded",
      "social trip with recovery breaks",
      "nightlife-ish but safe and relaxed",
      "some music, some quiet, not too expensive",
      "group wants fun evenings and slow afternoons",
      "avoid crazy crowd but keep evening options",
      "balanced friend trip with food and light nightlife",
      "we want social places, not tourist stampede",
      "not boring but not overwhelming",
      "friends trip, one person hates parties",
      "fun after sunset, calm before sunset"
    ]
  },
  {
    id: "weather-family-contradictions",
    intent: "family weather contradictions",
    interests: ["family", "cool weather", "easy"],
    constraints: { groupType: "family", energyLevel: "low", climatePreference: "cool" },
    relevantSourceIds: ["karnataka_003", "kerala_003", "himachal_003", "delhi_001", "rajasthan_004", "assam_001"],
    queries: [
      "family wants beach but grandma cannot take heat",
      "parents want cool weather, kids want things to see",
      "family trip where weather won't ruin everyone",
      "not too hot, not too much walking, still scenic",
      "kids get bored, parents get tired, need balance",
      "summer trip for family but avoid heat",
      "family wants nature but no tough treks",
      "cooler place with easy activities for parents",
      "parents prefer calm, kids want views",
      "family trip in warm month but need pleasant weather",
      "avoid humid beaches, family friendly please",
      "easy family vacation with cooler climate",
      "family wants photos and comfort",
      "low walking family trip with good weather",
      "not hot, not crowded, not boring for family",
      "parents and teenagers, need safe scenic place",
      "family holiday where we can rest often",
      "cool-ish destination for elders and kids",
      "gentle family itinerary with fresh air",
      "family wants peaceful weather and memorable views"
    ]
  },
  {
    id: "food-diet-messy",
    intent: "food dietary constraints",
    interests: ["food", "vegetarian", "market", "family"],
    constraints: { groupType: "friends", pace: "flexible" },
    relevantSourceIds: ["goa_004", "kerala_004", "maharashtra_001", "delhi_001", "goa_006", "rajasthan_002"],
    queries: [
      "one vegetarian and one picky eater in the group",
      "food matters, but not fancy restaurants",
      "need veg options, snacks, and walking around",
      "market food and easy cafes, group trip",
      "vegetarian-friendly destination with casual food",
      "we travel mostly to eat but budget is limited",
      "friends want street food, one person is vegetarian",
      "cafes, markets, snacks, not too premium",
      "food-focused but safe for picky parents",
      "vegetarian food should not be a struggle",
      "casual eating, markets, and photos",
      "we need good food and easy evening walks",
      "group has dietary drama, keep food flexible",
      "not a resort, we want local snacks",
      "food and shopping, low stress",
      "veg friendly city break with culture",
      "some food, some heritage, not too tiring",
      "friends want food lanes and good pictures",
      "cheap eats and markets for a weekend",
      "food-first trip, but one person hates crowds"
    ]
  },
  {
    id: "short-trip-logistics",
    intent: "short trip easy logistics",
    interests: ["city", "easy", "food", "heritage"],
    constraints: { duration: "weekend", pace: "balanced" },
    relevantSourceIds: ["maharashtra_001", "delhi_001", "rajasthan_002", "kerala_004", "goa_006", "rajasthan_004"],
    queries: [
      "only have 2 days, don't waste them in transit",
      "weekend trip with easy movement",
      "short trip, need food and one or two landmarks",
      "two days only, not a complicated itinerary",
      "quick getaway for people who hate planning",
      "48 hours, good photos and food",
      "weekend with cafes, walks, and one iconic spot",
      "short city break, low friction",
      "two-day trip for a couple, easy logistics",
      "we land Friday night and leave Sunday",
      "not too far between places, weekend only",
      "easy short trip with culture and food",
      "quick break, no long transfers",
      "two days, relaxed sightseeing",
      "weekend plan that still feels memorable",
      "city-ish trip with pretty evenings",
      "short vacation for tired working people",
      "one weekend, simple route, nice food",
      "easy logistics and good photos",
      "minimal travel time, maximum vibe"
    ]
  },
  {
    id: "repeat-traveler-hidden",
    intent: "repeat traveler hidden gems",
    interests: ["hidden", "offbeat", "local", "quiet"],
    constraints: { crowdLevel: "low", pace: "slow" },
    relevantSourceIds: ["goa_008", "arunachal_001", "meghalaya_001", "andaman_002", "goa_003", "karnataka_001"],
    queries: [
      "I don't want the obvious Instagram places",
      "suggest something that doesn't feel copy pasted",
      "I've done the famous spots, want quieter places",
      "hidden but not unsafe",
      "offbeat trip with local feel",
      "somewhere my friends probably haven't been",
      "quiet and different, not a checklist destination",
      "avoid the usual top ten tourist places",
      "I want something slower and less known",
      "hidden gem but still practical",
      "not mainstream, but not impossible to reach",
      "repeat traveler, need fresh ideas",
      "less touristy and more local",
      "underrated place with nature or culture",
      "I want a place that feels lived-in",
      "skip the iconic stuff, give me atmosphere",
      "quiet destination for someone who travels often",
      "offbeat but not boring",
      "not crowded, not over-marketed",
      "something with texture, not just sightseeing"
    ]
  },
  {
    id: "budget-couple-conflict",
    intent: "budget couple conflict",
    interests: ["romantic", "budget", "views"],
    constraints: { groupType: "couples", budgetBand: "low", pace: "slow" },
    relevantSourceIds: ["goa_003", "goa_002", "karnataka_002", "goa_007", "maharashtra_001", "delhi_001", "karnataka_001"],
    queries: [
      "romantic but we are not rich",
      "couple trip, low budget, still pretty",
      "my partner wants beautiful views, I have a tight budget",
      "cheap anniversary idea that doesn't feel cheap",
      "budget couple trip with sunset",
      "romantic and affordable, not luxury",
      "couple vacation under a tight budget",
      "want nice photos without premium hotels",
      "romantic vibe, simple stays, low spend",
      "my girlfriend wants cute, my wallet says no",
      "budget friendly place for two",
      "couple trip with low cost food and views",
      "not expensive but still memorable for us",
      "affordable sunset destination for a couple",
      "romantic weekend without resort prices",
      "we want slow and pretty, but budget first",
      "cheap couple plan with calm evenings",
      "romantic low-cost trip, no party scene",
      "two people, tight budget, scenic place",
      "budget date-trip but make it travel"
    ]
  }
];

export const hardRetrievalEvaluationPrompts = hardPromptGroups.flatMap((group) =>
  group.queries.map((query, index) => ({
    id: `${group.id}-${String(index + 1).padStart(2, "0")}`,
    benchmark: "hard-v2",
    intent: group.intent,
    query,
    interests: group.interests,
    constraints: group.constraints,
    expectedPlaceIds: group.relevantSourceIds,
    minimumHits: group.minimumHits ?? 1
  }))
);

export const hardRetrievalEvaluationCases = hardRetrievalEvaluationPrompts.map((prompt) => ({
  id: prompt.id,
  query: prompt.query,
  interests: prompt.interests,
  constraints: prompt.constraints,
  relevantSourceIds: prompt.expectedPlaceIds,
  minimumHits: prompt.minimumHits
}));

export default hardRetrievalEvaluationPrompts;
