export const demoPlaces = [
  {
    id: "demo-heritage-1",
    name: "Heritage Anchor",
    type: "heritage",
    role: "anchor",
    cluster: "Walled City",
    tags: ["heritage", "culture", "photography"],
    summary: "A high-context heritage stop for travelers who want cultural depth and strong visual moments.",
    bestFor: ["first-time visitors", "cultural explorers", "photography plans"],
    dayWindows: ["morning", "late afternoon"],
    retrievalTerms: ["fort", "palace", "history", "architecture", "old city"],
    fatigue: 0.62,
    estimatedCost: 650,
    durationMinutes: 150,
    popularity: 92,
    travelTimeFromCenterMinutes: 28,
    indoorOutdoor: "outdoor",
    costBand: "medium",
    openingWindows: ["morning", "afternoon"],
    groupFit: ["couple", "friends", "family"],
    clusterPriority: 88,
    weatherFit: 76
  },
  {
    id: "demo-food-1",
    name: "Local Food Stop",
    type: "food",
    role: "recovery",
    cluster: "Central District",
    tags: ["food", "local", "recovery"],
    summary: "A practical food break that helps rebalance the itinerary after denser sightseeing.",
    bestFor: ["food explorers", "low-energy groups", "midday reset"],
    dayWindows: ["lunch", "evening"],
    retrievalTerms: ["street food", "local food", "snacks", "meal break", "rest stop"],
    fatigue: 0.18,
    estimatedCost: 350,
    durationMinutes: 75,
    popularity: 84,
    travelTimeFromCenterMinutes: 12,
    indoorOutdoor: "mixed",
    costBand: "low",
    openingWindows: ["lunch", "evening"],
    groupFit: ["solo", "couple", "friends", "family"],
    clusterPriority: 82,
    weatherFit: 92
  },
  {
    id: "demo-view-1",
    name: "Sunset Viewpoint",
    type: "nature",
    role: "visual",
    cluster: "North Ridge",
    tags: ["photography", "sunset", "scenic"],
    summary: "A scenic viewpoint suited for golden-hour photos and slower visual exploration.",
    bestFor: ["photographers", "couples", "sunset plans"],
    dayWindows: ["late afternoon", "sunset"],
    retrievalTerms: ["viewpoint", "skyline", "golden hour", "landscape", "photo spot"],
    fatigue: 0.55,
    estimatedCost: 250,
    durationMinutes: 90,
    popularity: 78,
    travelTimeFromCenterMinutes: 34,
    indoorOutdoor: "outdoor",
    costBand: "low",
    openingWindows: ["late afternoon", "sunset"],
    groupFit: ["couple", "friends"],
    clusterPriority: 74,
    weatherFit: 68
  },
  {
    id: "demo-market-1",
    name: "Craft Market Walk",
    type: "shopping",
    role: "exploration",
    cluster: "Old Quarter",
    tags: ["shopping", "craft", "culture"],
    summary: "A market walk for craft discovery, local texture, and flexible browsing time.",
    bestFor: ["shoppers", "cultural explorers", "budget groups"],
    dayWindows: ["afternoon", "evening"],
    retrievalTerms: ["bazaar", "handicraft", "market", "souvenirs", "local walk"],
    fatigue: 0.48,
    estimatedCost: 500,
    durationMinutes: 120,
    popularity: 81,
    travelTimeFromCenterMinutes: 18,
    indoorOutdoor: "outdoor",
    costBand: "medium",
    openingWindows: ["afternoon", "evening"],
    groupFit: ["solo", "couple", "friends", "family"],
    clusterPriority: 79,
    weatherFit: 72
  },
  {
    id: "demo-cafe-1",
    name: "Slow Cafe Reset",
    type: "food",
    role: "recovery",
    cluster: "Cafe District",
    tags: ["cafe", "food", "low fatigue"],
    summary: "A low-fatigue cafe reset for slower pacing, conversation, and itinerary recovery.",
    bestFor: ["remote workers", "low-energy families", "slow travelers"],
    dayWindows: ["morning", "afternoon"],
    retrievalTerms: ["coffee", "cafe", "quiet", "rest", "low energy"],
    fatigue: 0.12,
    estimatedCost: 450,
    durationMinutes: 70,
    popularity: 76,
    travelTimeFromCenterMinutes: 16,
    indoorOutdoor: "indoor",
    costBand: "medium",
    openingWindows: ["morning", "afternoon", "evening"],
    groupFit: ["solo", "couple", "friends", "family"],
    clusterPriority: 84,
    weatherFit: 96
  },
  {
    id: "demo-culture-1",
    name: "Contemporary Arts Stop",
    type: "culture",
    role: "filler",
    cluster: "Central District",
    tags: ["culture", "indoor", "visual"],
    summary: "A flexible indoor cultural stop that works well as a weather-safe filler activity.",
    bestFor: ["art curious travelers", "rainy-day plans", "visual explorers"],
    dayWindows: ["afternoon", "early evening"],
    retrievalTerms: ["gallery", "art", "indoor", "museum", "creative stop"],
    fatigue: 0.28,
    estimatedCost: 400,
    durationMinutes: 95,
    popularity: 70,
    travelTimeFromCenterMinutes: 10,
    indoorOutdoor: "indoor",
    costBand: "low",
    openingWindows: ["afternoon", "early evening"],
    groupFit: ["solo", "couple", "friends"],
    clusterPriority: 83,
    weatherFit: 94
  }
];
